Repository eclipse/xtext-lib, pull requests merged in 2019-11, with the labels that each got.

#249 [eclipse/xtext#1573] Ensure that all plugins do have a ManifestBuilder
  gradle/eclipse-project-layout.gradle
  org.eclipse.xtend.lib.gwt/.project
  org.eclipse.xtend.lib.macro/.project
  org.eclipse.xtend.lib/.project
  org.eclipse.xtext.xbase.lib.gwt/.project
  org.eclipse.xtext.xbase.lib/.project
Labels: releng

#248 [eclipse/xtext#1574] Updated Platform Maven Dependencies to latest version (2019-09)
  releng/org.eclipse.xtext.dev-bom/pom.xml
Labels: releng

#262 [releng] Bootstrap against 2.20.0.M2
  gradle/versions.gradle
Labels: bot, releng

#265 added gradle properties
  gradle.properties
Labels: releng

#229 [eclipse/xtext-xtend#877] added 'contains' to array/iterable/iterator
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsBooleanTest.xtend
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsByteTest.xtend
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsCharTest.xtend
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsDoubleTest.xtend
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsFloatTest.xtend
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsIntTest.xtend
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsLongTest.xtend
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsObjectTest.xtend
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsShortTest.xtend
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IterableExtensionsTest.java
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IteratorExtensionsTest.java
  org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsBooleanTest.java
  org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsByteTest.java
  org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsCharTest.java
  org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsDoubleTest.java
  org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsFloatTest.java
  org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsIntTest.java
  org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsLongTest.java
  org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsObjectTest.java
  org.eclipse.xtext.xbase.lib.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/ArrayExtensionsShortTest.java
  org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/ArrayExtensions.java
  org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IterableExtensions.java
  org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IteratorExtensions.java
Labels: enhancement

#266 fixed unused imports
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IterableExtensionsTest.java
  org.eclipse.xtext.xbase.lib.tests/src/org/eclipse/xtext/xbase/tests/lib/IteratorExtensionsTest.java
Labels: releng

#270 cleanup versions.gradle
  gradle/versions.gradle
Labels: releng

#273 updated grgit gradle plugin to version 4.0.0
  build.gradle
Labels: releng

#263 [eclipse/xtext#1573] Provide proper build.properties
  org.eclipse.xtend.lib.gwt/build.properties
  org.eclipse.xtend.lib.macro/build.properties
  org.eclipse.xtend.lib/build.properties
  org.eclipse.xtext.xbase.lib.gwt/build.properties
  org.eclipse.xtext.xbase.lib/build.properties
Labels: releng

#274 [eclipse/xtext#1609] update to mwe 2.11.1
  releng/org.eclipse.xtext.dev-bom/pom.xml
Labels: releng

#276 [releng] Bootstrap against 2.20.0.M3
  gradle/versions.gradle
Labels: bot, releng
