Repository eclipse/xtext-lib, pull requests merged in 2020-01, with the labels that each got.

#283 [eclipse/xtext#1638] update to 2019-12 platform maven artifacts
  releng/org.eclipse.xtext.dev-bom/pom.xml
Labels: releng

#289 [releng] Bootstrap against 2.21.0.M1
  gradle/versions.gradle
Labels: bot, releng

#290 update grgit to 4.0.1
  build.gradle
Labels: releng

#291 bumped gwt gradle plugin
  org.eclipse.xtend.lib.gwt.test/build.gradle
Labels: releng

#287 [eclipse/xtext#1644] use java platform
  1-gradle-build.sh
  1-install-bom.sh
  2-maven-build.sh
  Jenkinsfile
  build.gradle
  gradle/versions.gradle
  org.eclipse.xtext.dev-bom/.project
  org.eclipse.xtext.dev-bom/.settings/org.eclipse.core.resources.prefs
  org.eclipse.xtext.dev-bom/build.gradle
  org.eclipse.xtext.xbase.lib/build.gradle
  releng/pom.xml
  settings.gradle
Labels: releng

#292 [eclipse/xtext#1643] update to tycho 1.6.0
  releng/pom.xml
Labels: releng

#294 removed bom (fixed merge issue)
  releng/org.eclipse.xtext.dev-bom/pom.xml
Labels: refactoring

#293 [eclipse/xtext#1595] Escape branch name for k8s label
  Jenkinsfile
Labels: releng
