Repository eclipse/xtext-lib, pull requests merged in 2020-06, with the labels that each got.

#331 [releng] Update Xtext version to 2.23.0
  gradle/versions.gradle
  org.eclipse.xtend.lib.gwt/META-INF/MANIFEST.MF
  org.eclipse.xtend.lib.macro/META-INF/MANIFEST.MF
  org.eclipse.xtend.lib/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.lib.gwt/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.lib/META-INF/MANIFEST.MF
  releng/org.eclipse.xtend.gwt/feature.xml
  releng/org.eclipse.xtend.gwt/pom.xml
  releng/org.eclipse.xtext.gwt/feature.xml
  releng/org.eclipse.xtext.gwt/pom.xml
  releng/org.eclipse.xtext.xbase.lib/feature.xml
  releng/org.eclipse.xtext.xbase.lib/pom.xml
  releng/p2/category.xml
  releng/p2/pom.xml
  releng/pom.xml
  releng/releng-target/pom.xml
Labels: bot, releng

#333 [eclipse/xtext#1781] update orbit to 2020-09
  releng/releng-target/xtext-lib.target.target
Labels: releng

#332 [eclipse/xtext#1801] increase build timeout
  Jenkinsfile
Labels: releng

#334 [eclipse/xtext#1802] Update build.gradle with new plugin versions.
  org.eclipse.xtext.dev-bom/build.gradle
Labels: releng

#335 [#903] Added missing since tag, improved backwards compatibility
  org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/MethodDeclaration.java
Labels: enhancement
